/**
 * gpio_base.cs
 *
 * Copyright (c) 2024 Mateusz Stadnik <matgla@live.com>
 *
 * Distributed under the terms of the MIT License.
 */


namespace Antmicro.Renode.Peripherals.GPIOPort
{
    public enum RpGpioFunction
    {
        SPI0_RX,
        SPI0_CSn,
        SPI0_SCK,
        SPI0_TX,
        SPI1_RX,
        SPI1_CSn,
        SPI1_SCK,
        SPI1_TX,
        UART0_TX,
        UART0_RX,
        UART0_CTS,
        UART0_RTS,
        UART1_TX,
        UART1_RX,
        UART1_CTS,
        UART1_RTS,
        I2C0_SDA,
        I2C0_SCL,
        I2C1_SDA,
        I2C1_SCL,
        PWM0_A,
        PWM0_B,
        PWM1_A,
        PWM1_B,
        PWM2_A,
        PWM2_B,
        PWM3_A,
        PWM3_B,
        PWM4_A,
        PWM4_B,
        PWM5_A,
        PWM5_B,
        PWM6_A,
        PWM6_B,
        PWM7_A,
        PWM7_B,
        PWM8_A,
        PWM8_B,
        PWM9_A,
        PWM9_B,
        PWM10_A,
        PWM10_B,
        PWM11_A,
        PWM11_B,
        SIO,
        PIO0,
        PIO1,
        PIO2,
        CLOCK_GPIN0,
        CLOCK_GPIN1,
        CLOCK_GPOUT0,
        CLOCK_GPOUT1,
        CLOCK_GPOUT2,
        CLOCK_GPOUT3,
        USB_OVCUR_DET,
        USB_VBUS_DET,
        USB_VBUS_EN,
        QMI_CS1n,
        TRACECLK,
        TRACEDATA0,
        TRACEDATA1,
        TRACEDATA2,
        TRACEDATA3,
        HSTX,
        NONE
    };

    public static class RpGpioFunctionBuilder
    {
        public static RpGpioFunction[,] BuildForRp2040()
        {
            var pinMapping = new RpGpioFunction[29, 9];
            pinMapping[0, 0] = RpGpioFunction.SPI0_RX;
            pinMapping[0, 1] = RpGpioFunction.UART0_TX;
            pinMapping[0, 2] = RpGpioFunction.I2C0_SDA;
            pinMapping[0, 3] = RpGpioFunction.PWM0_A;
            pinMapping[0, 4] = RpGpioFunction.SIO;
            pinMapping[0, 5] = RpGpioFunction.PIO0;
            pinMapping[0, 6] = RpGpioFunction.PIO1;
            pinMapping[0, 7] = RpGpioFunction.NONE;
            pinMapping[0, 8] = RpGpioFunction.USB_OVCUR_DET;
            pinMapping[1, 0] = RpGpioFunction.SPI0_CSn;
            pinMapping[1, 1] = RpGpioFunction.UART0_RX;
            pinMapping[1, 2] = RpGpioFunction.I2C0_SCL;
            pinMapping[1, 3] = RpGpioFunction.PWM0_B;
            pinMapping[1, 4] = RpGpioFunction.SIO;
            pinMapping[1, 5] = RpGpioFunction.PIO0;
            pinMapping[1, 6] = RpGpioFunction.PIO1;
            pinMapping[1, 7] = RpGpioFunction.NONE;
            pinMapping[1, 8] = RpGpioFunction.USB_VBUS_DET;
            pinMapping[2, 0] = RpGpioFunction.SPI0_SCK;
            pinMapping[2, 1] = RpGpioFunction.UART0_CTS;
            pinMapping[2, 2] = RpGpioFunction.I2C1_SDA;
            pinMapping[2, 3] = RpGpioFunction.PWM1_A;
            pinMapping[2, 4] = RpGpioFunction.SIO;
            pinMapping[2, 5] = RpGpioFunction.PIO0;
            pinMapping[2, 6] = RpGpioFunction.PIO1;
            pinMapping[2, 7] = RpGpioFunction.NONE;
            pinMapping[2, 8] = RpGpioFunction.USB_VBUS_EN;
            pinMapping[3, 0] = RpGpioFunction.SPI0_TX;
            pinMapping[3, 1] = RpGpioFunction.UART0_RTS;
            pinMapping[3, 2] = RpGpioFunction.I2C1_SCL;
            pinMapping[3, 3] = RpGpioFunction.PWM1_B;
            pinMapping[3, 4] = RpGpioFunction.SIO;
            pinMapping[3, 5] = RpGpioFunction.PIO0;
            pinMapping[3, 6] = RpGpioFunction.PIO1;
            pinMapping[3, 7] = RpGpioFunction.NONE;
            pinMapping[3, 8] = RpGpioFunction.USB_OVCUR_DET;
            pinMapping[4, 0] = RpGpioFunction.SPI0_RX;
            pinMapping[4, 1] = RpGpioFunction.UART1_TX;
            pinMapping[4, 2] = RpGpioFunction.I2C0_SDA;
            pinMapping[4, 3] = RpGpioFunction.PWM2_A;
            pinMapping[4, 4] = RpGpioFunction.SIO;
            pinMapping[4, 5] = RpGpioFunction.PIO0;
            pinMapping[4, 6] = RpGpioFunction.PIO1;
            pinMapping[4, 7] = RpGpioFunction.NONE;
            pinMapping[4, 8] = RpGpioFunction.USB_VBUS_DET;
            pinMapping[5, 0] = RpGpioFunction.SPI0_CSn;
            pinMapping[5, 1] = RpGpioFunction.UART1_RX;
            pinMapping[5, 2] = RpGpioFunction.I2C0_SCL;
            pinMapping[5, 3] = RpGpioFunction.PWM2_B;
            pinMapping[5, 4] = RpGpioFunction.SIO;
            pinMapping[5, 5] = RpGpioFunction.PIO0;
            pinMapping[5, 6] = RpGpioFunction.PIO1;
            pinMapping[5, 7] = RpGpioFunction.NONE;
            pinMapping[5, 8] = RpGpioFunction.USB_VBUS_EN;
            pinMapping[6, 0] = RpGpioFunction.SPI0_SCK;
            pinMapping[6, 1] = RpGpioFunction.UART1_CTS;
            pinMapping[6, 2] = RpGpioFunction.I2C1_SDA;
            pinMapping[6, 3] = RpGpioFunction.PWM3_A;
            pinMapping[6, 4] = RpGpioFunction.SIO;
            pinMapping[6, 5] = RpGpioFunction.PIO0;
            pinMapping[6, 6] = RpGpioFunction.PIO1;
            pinMapping[6, 7] = RpGpioFunction.NONE;
            pinMapping[6, 8] = RpGpioFunction.USB_OVCUR_DET;
            pinMapping[7, 0] = RpGpioFunction.SPI0_TX;
            pinMapping[7, 1] = RpGpioFunction.UART1_RTS;
            pinMapping[7, 2] = RpGpioFunction.I2C1_SCL;
            pinMapping[7, 3] = RpGpioFunction.PWM3_B;
            pinMapping[7, 4] = RpGpioFunction.SIO;
            pinMapping[7, 5] = RpGpioFunction.PIO0;
            pinMapping[7, 6] = RpGpioFunction.PIO1;
            pinMapping[7, 7] = RpGpioFunction.NONE;
            pinMapping[7, 8] = RpGpioFunction.USB_VBUS_DET;
            pinMapping[8, 0] = RpGpioFunction.SPI1_RX;
            pinMapping[8, 1] = RpGpioFunction.UART1_TX;
            pinMapping[8, 2] = RpGpioFunction.I2C0_SDA;
            pinMapping[8, 3] = RpGpioFunction.PWM4_A;
            pinMapping[8, 4] = RpGpioFunction.SIO;
            pinMapping[8, 5] = RpGpioFunction.PIO0;
            pinMapping[8, 6] = RpGpioFunction.PIO1;
            pinMapping[8, 7] = RpGpioFunction.NONE;
            pinMapping[8, 8] = RpGpioFunction.USB_VBUS_EN;
            pinMapping[9, 0] = RpGpioFunction.SPI1_CSn;
            pinMapping[9, 1] = RpGpioFunction.UART1_RX;
            pinMapping[9, 2] = RpGpioFunction.I2C0_SCL;
            pinMapping[9, 3] = RpGpioFunction.PWM4_B;
            pinMapping[9, 4] = RpGpioFunction.SIO;
            pinMapping[9, 5] = RpGpioFunction.PIO0;
            pinMapping[9, 6] = RpGpioFunction.PIO1;
            pinMapping[9, 7] = RpGpioFunction.NONE;
            pinMapping[9, 8] = RpGpioFunction.USB_OVCUR_DET;
            pinMapping[10, 0] = RpGpioFunction.SPI1_SCK;
            pinMapping[10, 1] = RpGpioFunction.UART1_CTS;
            pinMapping[10, 2] = RpGpioFunction.I2C1_SDA;
            pinMapping[10, 3] = RpGpioFunction.PWM5_A;
            pinMapping[10, 4] = RpGpioFunction.SIO;
            pinMapping[10, 5] = RpGpioFunction.PIO0;
            pinMapping[10, 6] = RpGpioFunction.PIO1;
            pinMapping[10, 7] = RpGpioFunction.NONE;
            pinMapping[10, 8] = RpGpioFunction.USB_VBUS_DET;
            pinMapping[11, 0] = RpGpioFunction.SPI1_TX;
            pinMapping[11, 1] = RpGpioFunction.UART1_RTS;
            pinMapping[11, 2] = RpGpioFunction.I2C1_SCL;
            pinMapping[11, 3] = RpGpioFunction.PWM5_B;
            pinMapping[11, 4] = RpGpioFunction.SIO;
            pinMapping[11, 5] = RpGpioFunction.PIO0;
            pinMapping[11, 6] = RpGpioFunction.PIO1;
            pinMapping[11, 7] = RpGpioFunction.NONE;
            pinMapping[11, 8] = RpGpioFunction.USB_VBUS_EN;
            pinMapping[12, 0] = RpGpioFunction.SPI1_RX;
            pinMapping[12, 1] = RpGpioFunction.UART0_TX;
            pinMapping[12, 2] = RpGpioFunction.I2C0_SDA;
            pinMapping[12, 3] = RpGpioFunction.PWM6_A;
            pinMapping[12, 4] = RpGpioFunction.SIO;
            pinMapping[12, 5] = RpGpioFunction.PIO0;
            pinMapping[12, 6] = RpGpioFunction.PIO1;
            pinMapping[12, 7] = RpGpioFunction.NONE;
            pinMapping[12, 8] = RpGpioFunction.USB_OVCUR_DET;
            pinMapping[13, 0] = RpGpioFunction.SPI1_CSn;
            pinMapping[13, 1] = RpGpioFunction.UART0_RX;
            pinMapping[13, 2] = RpGpioFunction.I2C0_SCL;
            pinMapping[13, 3] = RpGpioFunction.PWM6_B;
            pinMapping[13, 4] = RpGpioFunction.SIO;
            pinMapping[13, 5] = RpGpioFunction.PIO0;
            pinMapping[13, 6] = RpGpioFunction.PIO1;
            pinMapping[13, 7] = RpGpioFunction.NONE;
            pinMapping[13, 8] = RpGpioFunction.USB_VBUS_DET;
            pinMapping[14, 0] = RpGpioFunction.SPI1_SCK;
            pinMapping[14, 1] = RpGpioFunction.UART0_CTS;
            pinMapping[14, 2] = RpGpioFunction.I2C1_SDA;
            pinMapping[14, 3] = RpGpioFunction.PWM7_A;
            pinMapping[14, 4] = RpGpioFunction.SIO;
            pinMapping[14, 5] = RpGpioFunction.PIO0;
            pinMapping[14, 6] = RpGpioFunction.PIO1;
            pinMapping[14, 7] = RpGpioFunction.NONE;
            pinMapping[14, 8] = RpGpioFunction.USB_VBUS_EN;
            pinMapping[15, 0] = RpGpioFunction.SPI1_TX;
            pinMapping[15, 1] = RpGpioFunction.UART0_RTS;
            pinMapping[15, 2] = RpGpioFunction.I2C1_SCL;
            pinMapping[15, 3] = RpGpioFunction.PWM7_B;
            pinMapping[15, 4] = RpGpioFunction.SIO;
            pinMapping[15, 5] = RpGpioFunction.PIO0;
            pinMapping[15, 6] = RpGpioFunction.PIO1;
            pinMapping[15, 7] = RpGpioFunction.NONE;
            pinMapping[15, 8] = RpGpioFunction.USB_OVCUR_DET;
            pinMapping[16, 0] = RpGpioFunction.SPI0_RX;
            pinMapping[16, 1] = RpGpioFunction.UART0_TX;
            pinMapping[16, 2] = RpGpioFunction.I2C0_SDA;
            pinMapping[16, 3] = RpGpioFunction.PWM0_A;
            pinMapping[16, 4] = RpGpioFunction.SIO;
            pinMapping[16, 5] = RpGpioFunction.PIO0;
            pinMapping[16, 6] = RpGpioFunction.PIO1;
            pinMapping[16, 7] = RpGpioFunction.NONE;
            pinMapping[16, 8] = RpGpioFunction.USB_VBUS_DET;
            pinMapping[17, 0] = RpGpioFunction.SPI0_CSn;
            pinMapping[17, 1] = RpGpioFunction.UART0_RX;
            pinMapping[17, 2] = RpGpioFunction.I2C0_SCL;
            pinMapping[17, 3] = RpGpioFunction.PWM0_B;
            pinMapping[17, 4] = RpGpioFunction.SIO;
            pinMapping[17, 5] = RpGpioFunction.PIO0;
            pinMapping[17, 6] = RpGpioFunction.PIO1;
            pinMapping[17, 7] = RpGpioFunction.NONE;
            pinMapping[17, 8] = RpGpioFunction.USB_VBUS_EN;
            pinMapping[18, 0] = RpGpioFunction.SPI0_SCK;
            pinMapping[18, 1] = RpGpioFunction.UART0_CTS;
            pinMapping[18, 2] = RpGpioFunction.I2C1_SDA;
            pinMapping[18, 3] = RpGpioFunction.PWM1_A;
            pinMapping[18, 4] = RpGpioFunction.SIO;
            pinMapping[18, 5] = RpGpioFunction.PIO0;
            pinMapping[18, 6] = RpGpioFunction.PIO1;
            pinMapping[18, 7] = RpGpioFunction.NONE;
            pinMapping[18, 8] = RpGpioFunction.USB_OVCUR_DET;
            pinMapping[19, 0] = RpGpioFunction.SPI0_TX;
            pinMapping[19, 1] = RpGpioFunction.UART0_RTS;
            pinMapping[19, 2] = RpGpioFunction.I2C1_SCL;
            pinMapping[19, 3] = RpGpioFunction.PWM1_B;
            pinMapping[19, 4] = RpGpioFunction.SIO;
            pinMapping[19, 5] = RpGpioFunction.PIO0;
            pinMapping[19, 6] = RpGpioFunction.PIO1;
            pinMapping[19, 7] = RpGpioFunction.NONE;
            pinMapping[19, 8] = RpGpioFunction.USB_VBUS_DET;
            pinMapping[20, 0] = RpGpioFunction.SPI0_RX;
            pinMapping[20, 1] = RpGpioFunction.UART1_TX;
            pinMapping[20, 2] = RpGpioFunction.I2C0_SDA;
            pinMapping[20, 3] = RpGpioFunction.PWM2_A;
            pinMapping[20, 4] = RpGpioFunction.SIO;
            pinMapping[20, 5] = RpGpioFunction.PIO0;
            pinMapping[20, 6] = RpGpioFunction.PIO1;
            pinMapping[20, 7] = RpGpioFunction.CLOCK_GPIN0;
            pinMapping[20, 8] = RpGpioFunction.USB_VBUS_EN;
            pinMapping[21, 0] = RpGpioFunction.SPI0_CSn;
            pinMapping[21, 1] = RpGpioFunction.UART1_RX;
            pinMapping[21, 2] = RpGpioFunction.I2C0_SCL;
            pinMapping[21, 3] = RpGpioFunction.PWM2_B;
            pinMapping[21, 4] = RpGpioFunction.SIO;
            pinMapping[21, 5] = RpGpioFunction.PIO0;
            pinMapping[21, 6] = RpGpioFunction.PIO1;
            pinMapping[21, 7] = RpGpioFunction.CLOCK_GPOUT0;
            pinMapping[21, 8] = RpGpioFunction.USB_OVCUR_DET;
            pinMapping[22, 0] = RpGpioFunction.SPI0_SCK;
            pinMapping[22, 1] = RpGpioFunction.UART1_CTS;
            pinMapping[22, 2] = RpGpioFunction.I2C1_SDA;
            pinMapping[22, 3] = RpGpioFunction.PWM3_A;
            pinMapping[22, 4] = RpGpioFunction.SIO;
            pinMapping[22, 5] = RpGpioFunction.PIO0;
            pinMapping[22, 6] = RpGpioFunction.PIO1;
            pinMapping[22, 7] = RpGpioFunction.CLOCK_GPIN1;
            pinMapping[22, 8] = RpGpioFunction.USB_VBUS_DET;
            pinMapping[23, 0] = RpGpioFunction.SPI0_TX;
            pinMapping[23, 1] = RpGpioFunction.UART1_RTS;
            pinMapping[23, 2] = RpGpioFunction.I2C1_SCL;
            pinMapping[23, 3] = RpGpioFunction.PWM3_B;
            pinMapping[23, 4] = RpGpioFunction.SIO;
            pinMapping[23, 5] = RpGpioFunction.PIO0;
            pinMapping[23, 6] = RpGpioFunction.PIO1;
            pinMapping[23, 7] = RpGpioFunction.CLOCK_GPOUT1;
            pinMapping[23, 8] = RpGpioFunction.USB_VBUS_EN;
            pinMapping[24, 0] = RpGpioFunction.SPI1_RX;
            pinMapping[24, 1] = RpGpioFunction.UART1_TX;
            pinMapping[24, 2] = RpGpioFunction.I2C0_SDA;
            pinMapping[24, 3] = RpGpioFunction.PWM4_A;
            pinMapping[24, 4] = RpGpioFunction.SIO;
            pinMapping[24, 5] = RpGpioFunction.PIO0;
            pinMapping[24, 6] = RpGpioFunction.PIO1;
            pinMapping[24, 7] = RpGpioFunction.CLOCK_GPOUT2;
            pinMapping[24, 8] = RpGpioFunction.USB_OVCUR_DET;
            pinMapping[25, 0] = RpGpioFunction.SPI1_CSn;
            pinMapping[25, 1] = RpGpioFunction.UART1_RX;
            pinMapping[25, 2] = RpGpioFunction.I2C0_SCL;
            pinMapping[25, 3] = RpGpioFunction.PWM4_B;
            pinMapping[25, 4] = RpGpioFunction.SIO;
            pinMapping[25, 5] = RpGpioFunction.PIO0;
            pinMapping[25, 6] = RpGpioFunction.PIO1;
            pinMapping[25, 7] = RpGpioFunction.CLOCK_GPOUT3;
            pinMapping[25, 8] = RpGpioFunction.USB_VBUS_DET;
            pinMapping[26, 0] = RpGpioFunction.SPI1_SCK;
            pinMapping[26, 1] = RpGpioFunction.UART1_CTS;
            pinMapping[26, 2] = RpGpioFunction.I2C1_SDA;
            pinMapping[26, 3] = RpGpioFunction.PWM5_A;
            pinMapping[26, 4] = RpGpioFunction.SIO;
            pinMapping[26, 5] = RpGpioFunction.PIO0;
            pinMapping[26, 6] = RpGpioFunction.PIO1;
            pinMapping[26, 7] = RpGpioFunction.NONE;
            pinMapping[26, 8] = RpGpioFunction.USB_VBUS_EN;
            pinMapping[27, 0] = RpGpioFunction.SPI1_TX;
            pinMapping[27, 1] = RpGpioFunction.UART1_RTS;
            pinMapping[27, 2] = RpGpioFunction.I2C1_SCL;
            pinMapping[27, 3] = RpGpioFunction.PWM5_B;
            pinMapping[27, 4] = RpGpioFunction.SIO;
            pinMapping[27, 5] = RpGpioFunction.PIO0;
            pinMapping[27, 6] = RpGpioFunction.PIO1;
            pinMapping[27, 7] = RpGpioFunction.NONE;
            pinMapping[27, 8] = RpGpioFunction.USB_OVCUR_DET;
            pinMapping[28, 0] = RpGpioFunction.SPI1_RX;
            pinMapping[28, 1] = RpGpioFunction.UART0_TX;
            pinMapping[28, 2] = RpGpioFunction.I2C0_SDA;
            pinMapping[28, 3] = RpGpioFunction.PWM6_A;
            pinMapping[28, 4] = RpGpioFunction.SIO;
            pinMapping[28, 5] = RpGpioFunction.PIO0;
            pinMapping[28, 6] = RpGpioFunction.PIO1;
            pinMapping[28, 7] = RpGpioFunction.NONE;
            pinMapping[28, 8] = RpGpioFunction.USB_VBUS_DET;
            pinMapping[29, 0] = RpGpioFunction.SPI1_CSn;
            pinMapping[29, 1] = RpGpioFunction.UART0_RX;
            pinMapping[29, 2] = RpGpioFunction.I2C0_SCL;
            pinMapping[29, 3] = RpGpioFunction.PWM6_B;
            pinMapping[29, 4] = RpGpioFunction.SIO;
            pinMapping[29, 5] = RpGpioFunction.PIO0;
            pinMapping[29, 6] = RpGpioFunction.PIO1;
            pinMapping[29, 7] = RpGpioFunction.NONE;
            pinMapping[29, 8] = RpGpioFunction.USB_VBUS_EN;
            return pinMapping;
        }

        public static RpGpioFunction[,] BuildForRp2350()
        {
            var pinMapping = new RpGpioFunction[47, 12];
            pinMapping[0, 0] = RpGpioFunction.NONE;
            pinMapping[0, 1] = RpGpioFunction.SPI0_RX;
            pinMapping[0, 2] = RpGpioFunction.UART0_TX;
            pinMapping[0, 3] = RpGpioFunction.I2C0_SDA;
            pinMapping[0, 4] = RpGpioFunction.PWM0_A;
            pinMapping[0, 5] = RpGpioFunction.SIO;
            pinMapping[0, 6] = RpGpioFunction.PIO0;
            pinMapping[0, 7] = RpGpioFunction.PIO1;
            pinMapping[0, 8] = RpGpioFunction.PIO2;
            pinMapping[0, 9] = RpGpioFunction.QMI_CS1n;
            pinMapping[0, 10] = RpGpioFunction.USB_OVCUR_DET;
            pinMapping[0, 11] = RpGpioFunction.NONE;
            pinMapping[1, 0] = RpGpioFunction.NONE;
            pinMapping[1, 1] = RpGpioFunction.SPI0_CSn;
            pinMapping[1, 2] = RpGpioFunction.UART0_RX;
            pinMapping[1, 3] = RpGpioFunction.I2C0_SCL;
            pinMapping[1, 4] = RpGpioFunction.PWM0_B;
            pinMapping[1, 5] = RpGpioFunction.SIO;
            pinMapping[1, 6] = RpGpioFunction.PIO0;
            pinMapping[1, 7] = RpGpioFunction.PIO1;
            pinMapping[1, 8] = RpGpioFunction.PIO2;
            pinMapping[1, 9] = RpGpioFunction.TRACECLK;
            pinMapping[1, 10] = RpGpioFunction.USB_VBUS_DET;
            pinMapping[1, 11] = RpGpioFunction.NONE;
            pinMapping[2, 0] = RpGpioFunction.NONE;
            pinMapping[2, 1] = RpGpioFunction.SPI0_SCK;
            pinMapping[2, 2] = RpGpioFunction.UART0_CTS;
            pinMapping[2, 3] = RpGpioFunction.I2C1_SDA;
            pinMapping[2, 4] = RpGpioFunction.PWM1_A;
            pinMapping[2, 5] = RpGpioFunction.SIO;
            pinMapping[2, 6] = RpGpioFunction.PIO0;
            pinMapping[2, 7] = RpGpioFunction.PIO1;
            pinMapping[2, 8] = RpGpioFunction.PIO2;
            pinMapping[2, 9] = RpGpioFunction.TRACEDATA0;
            pinMapping[2, 10] = RpGpioFunction.USB_VBUS_EN;
            pinMapping[2, 11] = RpGpioFunction.UART0_TX;
            pinMapping[3, 0] = RpGpioFunction.NONE;
            pinMapping[3, 1] = RpGpioFunction.SPI0_TX;
            pinMapping[3, 2] = RpGpioFunction.UART0_RTS;
            pinMapping[3, 3] = RpGpioFunction.I2C1_SCL;
            pinMapping[3, 4] = RpGpioFunction.PWM1_B;
            pinMapping[3, 5] = RpGpioFunction.SIO;
            pinMapping[3, 6] = RpGpioFunction.PIO0;
            pinMapping[3, 7] = RpGpioFunction.PIO1;
            pinMapping[3, 8] = RpGpioFunction.PIO2;
            pinMapping[3, 9] = RpGpioFunction.TRACEDATA1;
            pinMapping[3, 10] = RpGpioFunction.USB_OVCUR_DET;
            pinMapping[3, 11] = RpGpioFunction.UART0_RX;
            pinMapping[4, 0] = RpGpioFunction.NONE;
            pinMapping[4, 1] = RpGpioFunction.SPI0_RX;
            pinMapping[4, 2] = RpGpioFunction.UART1_TX;
            pinMapping[4, 3] = RpGpioFunction.I2C0_SDA;
            pinMapping[4, 4] = RpGpioFunction.PWM2_A;
            pinMapping[4, 5] = RpGpioFunction.SIO;
            pinMapping[4, 6] = RpGpioFunction.PIO0;
            pinMapping[4, 7] = RpGpioFunction.PIO1;
            pinMapping[4, 8] = RpGpioFunction.PIO2;
            pinMapping[4, 9] = RpGpioFunction.TRACEDATA2;
            pinMapping[4, 10] = RpGpioFunction.USB_VBUS_DET;
            pinMapping[4, 11] = RpGpioFunction.NONE;
            pinMapping[5, 0] = RpGpioFunction.NONE;
            pinMapping[5, 1] = RpGpioFunction.SPI0_CSn;
            pinMapping[5, 2] = RpGpioFunction.UART1_RX;
            pinMapping[5, 3] = RpGpioFunction.I2C0_SCL;
            pinMapping[5, 4] = RpGpioFunction.PWM2_B;
            pinMapping[5, 5] = RpGpioFunction.SIO;
            pinMapping[5, 6] = RpGpioFunction.PIO0;
            pinMapping[5, 7] = RpGpioFunction.PIO1;
            pinMapping[5, 8] = RpGpioFunction.PIO2;
            pinMapping[5, 9] = RpGpioFunction.TRACEDATA3;
            pinMapping[5, 10] = RpGpioFunction.USB_VBUS_EN;
            pinMapping[5, 11] = RpGpioFunction.NONE;
            pinMapping[6, 0] = RpGpioFunction.NONE;
            pinMapping[6, 1] = RpGpioFunction.SPI0_SCK;
            pinMapping[6, 2] = RpGpioFunction.UART1_CTS;
            pinMapping[6, 3] = RpGpioFunction.I2C1_SDA;
            pinMapping[6, 4] = RpGpioFunction.PWM3_A;
            pinMapping[6, 5] = RpGpioFunction.SIO;
            pinMapping[6, 6] = RpGpioFunction.PIO0;
            pinMapping[6, 7] = RpGpioFunction.PIO1;
            pinMapping[6, 8] = RpGpioFunction.PIO2;
            pinMapping[6, 9] = RpGpioFunction.NONE;
            pinMapping[6, 10] = RpGpioFunction.USB_OVCUR_DET;
            pinMapping[6, 11] = RpGpioFunction.UART1_TX;
            pinMapping[7, 0] = RpGpioFunction.NONE;
            pinMapping[7, 1] = RpGpioFunction.SPI0_TX;
            pinMapping[7, 2] = RpGpioFunction.UART1_RTS;
            pinMapping[7, 3] = RpGpioFunction.I2C1_SCL;
            pinMapping[7, 4] = RpGpioFunction.PWM3_B;
            pinMapping[7, 5] = RpGpioFunction.SIO;
            pinMapping[7, 6] = RpGpioFunction.PIO0;
            pinMapping[7, 7] = RpGpioFunction.PIO1;
            pinMapping[7, 8] = RpGpioFunction.PIO2;
            pinMapping[7, 9] = RpGpioFunction.NONE;
            pinMapping[7, 10] = RpGpioFunction.USB_VBUS_DET;
            pinMapping[7, 11] = RpGpioFunction.UART1_RX;
            pinMapping[8, 0] = RpGpioFunction.NONE;
            pinMapping[8, 1] = RpGpioFunction.SPI1_RX;
            pinMapping[8, 2] = RpGpioFunction.UART1_TX;
            pinMapping[8, 3] = RpGpioFunction.I2C0_SDA;
            pinMapping[8, 4] = RpGpioFunction.PWM4_A;
            pinMapping[8, 5] = RpGpioFunction.SIO;
            pinMapping[8, 6] = RpGpioFunction.PIO0;
            pinMapping[8, 7] = RpGpioFunction.PIO1;
            pinMapping[8, 8] = RpGpioFunction.PIO2;
            pinMapping[8, 9] = RpGpioFunction.QMI_CS1n;
            pinMapping[8, 10] = RpGpioFunction.USB_VBUS_EN;
            pinMapping[8, 11] = RpGpioFunction.NONE;
            pinMapping[9, 0] = RpGpioFunction.NONE;
            pinMapping[9, 1] = RpGpioFunction.SPI1_CSn;
            pinMapping[9, 2] = RpGpioFunction.UART1_RX;
            pinMapping[9, 3] = RpGpioFunction.I2C0_SCL;
            pinMapping[9, 4] = RpGpioFunction.PWM4_B;
            pinMapping[9, 5] = RpGpioFunction.SIO;
            pinMapping[9, 6] = RpGpioFunction.PIO0;
            pinMapping[9, 7] = RpGpioFunction.PIO1;
            pinMapping[9, 8] = RpGpioFunction.PIO2;
            pinMapping[9, 9] = RpGpioFunction.NONE;
            pinMapping[9, 10] = RpGpioFunction.USB_OVCUR_DET;
            pinMapping[9, 11] = RpGpioFunction.NONE;
            pinMapping[10, 0] = RpGpioFunction.NONE;
            pinMapping[10, 1] = RpGpioFunction.SPI1_SCK;
            pinMapping[10, 2] = RpGpioFunction.UART1_CTS;
            pinMapping[10, 3] = RpGpioFunction.I2C1_SDA;
            pinMapping[10, 4] = RpGpioFunction.PWM5_A;
            pinMapping[10, 5] = RpGpioFunction.SIO;
            pinMapping[10, 6] = RpGpioFunction.PIO0;
            pinMapping[10, 7] = RpGpioFunction.PIO1;
            pinMapping[10, 8] = RpGpioFunction.PIO2;
            pinMapping[10, 9] = RpGpioFunction.NONE;
            pinMapping[10, 10] = RpGpioFunction.USB_VBUS_DET;
            pinMapping[10, 11] = RpGpioFunction.UART1_TX;
            pinMapping[11, 0] = RpGpioFunction.NONE;
            pinMapping[11, 1] = RpGpioFunction.SPI1_TX;
            pinMapping[11, 2] = RpGpioFunction.UART1_RTS;
            pinMapping[11, 3] = RpGpioFunction.I2C1_SCL;
            pinMapping[11, 4] = RpGpioFunction.PWM5_B;
            pinMapping[11, 5] = RpGpioFunction.SIO;
            pinMapping[11, 6] = RpGpioFunction.PIO0;
            pinMapping[11, 7] = RpGpioFunction.PIO1;
            pinMapping[11, 8] = RpGpioFunction.PIO2;
            pinMapping[11, 9] = RpGpioFunction.NONE;
            pinMapping[11, 10] = RpGpioFunction.USB_VBUS_EN;
            pinMapping[11, 11] = RpGpioFunction.UART1_RX;
            pinMapping[12, 0] = RpGpioFunction.HSTX;
            pinMapping[12, 1] = RpGpioFunction.SPI1_RX;
            pinMapping[12, 2] = RpGpioFunction.UART0_TX;
            pinMapping[12, 3] = RpGpioFunction.I2C0_SDA;
            pinMapping[12, 4] = RpGpioFunction.PWM6_A;
            pinMapping[12, 5] = RpGpioFunction.SIO;
            pinMapping[12, 6] = RpGpioFunction.PIO0;
            pinMapping[12, 7] = RpGpioFunction.PIO1;
            pinMapping[12, 8] = RpGpioFunction.PIO2;
            pinMapping[12, 9] = RpGpioFunction.CLOCK_GPIN0;
            pinMapping[12, 10] = RpGpioFunction.USB_OVCUR_DET;
            pinMapping[12, 11] = RpGpioFunction.NONE;
            pinMapping[13, 0] = RpGpioFunction.HSTX;
            pinMapping[13, 1] = RpGpioFunction.SPI1_CSn;
            pinMapping[13, 2] = RpGpioFunction.UART0_RX;
            pinMapping[13, 3] = RpGpioFunction.I2C0_SCL;
            pinMapping[13, 4] = RpGpioFunction.PWM6_B;
            pinMapping[13, 5] = RpGpioFunction.SIO;
            pinMapping[13, 6] = RpGpioFunction.PIO0;
            pinMapping[13, 7] = RpGpioFunction.PIO1;
            pinMapping[13, 8] = RpGpioFunction.PIO2;
            pinMapping[13, 9] = RpGpioFunction.CLOCK_GPOUT0;
            pinMapping[13, 10] = RpGpioFunction.USB_VBUS_DET;
            pinMapping[13, 11] = RpGpioFunction.NONE;
            pinMapping[14, 0] = RpGpioFunction.HSTX;
            pinMapping[14, 1] = RpGpioFunction.SPI1_SCK;
            pinMapping[14, 2] = RpGpioFunction.UART0_CTS;
            pinMapping[14, 3] = RpGpioFunction.I2C1_SDA;
            pinMapping[14, 4] = RpGpioFunction.PWM7_A;
            pinMapping[14, 5] = RpGpioFunction.SIO;
            pinMapping[14, 6] = RpGpioFunction.PIO0;
            pinMapping[14, 7] = RpGpioFunction.PIO1;
            pinMapping[14, 8] = RpGpioFunction.PIO2;
            pinMapping[14, 9] = RpGpioFunction.CLOCK_GPIN1;
            pinMapping[14, 10] = RpGpioFunction.USB_VBUS_EN;
            pinMapping[14, 11] = RpGpioFunction.UART0_TX;
            pinMapping[15, 0] = RpGpioFunction.HSTX;
            pinMapping[15, 1] = RpGpioFunction.SPI1_TX;
            pinMapping[15, 2] = RpGpioFunction.UART0_RTS;
            pinMapping[15, 3] = RpGpioFunction.I2C1_SCL;
            pinMapping[15, 4] = RpGpioFunction.PWM7_B;
            pinMapping[15, 5] = RpGpioFunction.SIO;
            pinMapping[15, 6] = RpGpioFunction.PIO0;
            pinMapping[15, 7] = RpGpioFunction.PIO1;
            pinMapping[15, 8] = RpGpioFunction.PIO2;
            pinMapping[15, 9] = RpGpioFunction.NONE;
            pinMapping[15, 10] = RpGpioFunction.USB_OVCUR_DET;
            pinMapping[15, 11] = RpGpioFunction.UART0_RX;
            pinMapping[16, 0] = RpGpioFunction.HSTX;
            pinMapping[16, 1] = RpGpioFunction.SPI0_RX;
            pinMapping[16, 2] = RpGpioFunction.UART0_TX;
            pinMapping[16, 3] = RpGpioFunction.I2C0_SDA;
            pinMapping[16, 4] = RpGpioFunction.PWM0_A;
            pinMapping[16, 5] = RpGpioFunction.SIO;
            pinMapping[16, 6] = RpGpioFunction.PIO0;
            pinMapping[16, 7] = RpGpioFunction.PIO1;
            pinMapping[16, 8] = RpGpioFunction.PIO2;
            pinMapping[16, 9] = RpGpioFunction.NONE;
            pinMapping[16, 10] = RpGpioFunction.USB_VBUS_DET;
            pinMapping[16, 11] = RpGpioFunction.NONE;
            pinMapping[17, 0] = RpGpioFunction.HSTX;
            pinMapping[17, 1] = RpGpioFunction.SPI0_CSn;
            pinMapping[17, 2] = RpGpioFunction.UART0_RX;
            pinMapping[17, 3] = RpGpioFunction.I2C0_SCL;
            pinMapping[17, 4] = RpGpioFunction.PWM0_B;
            pinMapping[17, 5] = RpGpioFunction.SIO;
            pinMapping[17, 6] = RpGpioFunction.PIO0;
            pinMapping[17, 7] = RpGpioFunction.PIO1;
            pinMapping[17, 8] = RpGpioFunction.PIO2;
            pinMapping[17, 9] = RpGpioFunction.NONE;
            pinMapping[17, 10] = RpGpioFunction.USB_VBUS_EN;
            pinMapping[17, 11] = RpGpioFunction.NONE;
            pinMapping[18, 0] = RpGpioFunction.HSTX;
            pinMapping[18, 1] = RpGpioFunction.SPI0_SCK;
            pinMapping[18, 2] = RpGpioFunction.UART0_CTS;
            pinMapping[18, 3] = RpGpioFunction.I2C1_SDA;
            pinMapping[18, 4] = RpGpioFunction.PWM1_A;
            pinMapping[18, 5] = RpGpioFunction.SIO;
            pinMapping[18, 6] = RpGpioFunction.PIO0;
            pinMapping[18, 7] = RpGpioFunction.PIO1;
            pinMapping[18, 8] = RpGpioFunction.PIO2;
            pinMapping[18, 9] = RpGpioFunction.NONE;
            pinMapping[18, 10] = RpGpioFunction.USB_OVCUR_DET;
            pinMapping[18, 11] = RpGpioFunction.UART0_TX;
            pinMapping[19, 0] = RpGpioFunction.HSTX;
            pinMapping[19, 1] = RpGpioFunction.SPI0_TX;
            pinMapping[19, 2] = RpGpioFunction.UART0_RTS;
            pinMapping[19, 3] = RpGpioFunction.I2C1_SCL;
            pinMapping[19, 4] = RpGpioFunction.PWM1_B;
            pinMapping[19, 5] = RpGpioFunction.SIO;
            pinMapping[19, 6] = RpGpioFunction.PIO0;
            pinMapping[19, 7] = RpGpioFunction.PIO1;
            pinMapping[19, 8] = RpGpioFunction.PIO2;
            pinMapping[19, 9] = RpGpioFunction.QMI_CS1n;
            pinMapping[19, 10] = RpGpioFunction.USB_VBUS_DET;
            pinMapping[19, 11] = RpGpioFunction.UART0_RX;
            pinMapping[20, 0] = RpGpioFunction.NONE;
            pinMapping[20, 1] = RpGpioFunction.SPI0_RX;
            pinMapping[20, 2] = RpGpioFunction.UART1_TX;
            pinMapping[20, 3] = RpGpioFunction.I2C0_SDA;
            pinMapping[20, 4] = RpGpioFunction.PWM2_A;
            pinMapping[20, 5] = RpGpioFunction.SIO;
            pinMapping[20, 6] = RpGpioFunction.PIO0;
            pinMapping[20, 7] = RpGpioFunction.PIO1;
            pinMapping[20, 8] = RpGpioFunction.PIO2;
            pinMapping[20, 9] = RpGpioFunction.CLOCK_GPIN0;
            pinMapping[20, 10] = RpGpioFunction.USB_VBUS_EN;
            pinMapping[20, 11] = RpGpioFunction.NONE;
            pinMapping[21, 0] = RpGpioFunction.NONE;
            pinMapping[21, 1] = RpGpioFunction.SPI0_CSn;
            pinMapping[21, 2] = RpGpioFunction.UART1_RX;
            pinMapping[21, 3] = RpGpioFunction.I2C0_SCL;
            pinMapping[21, 4] = RpGpioFunction.PWM2_B;
            pinMapping[21, 5] = RpGpioFunction.SIO;
            pinMapping[21, 6] = RpGpioFunction.PIO0;
            pinMapping[21, 7] = RpGpioFunction.PIO1;
            pinMapping[21, 8] = RpGpioFunction.PIO2;
            pinMapping[21, 9] = RpGpioFunction.CLOCK_GPOUT0;
            pinMapping[21, 10] = RpGpioFunction.USB_OVCUR_DET;
            pinMapping[21, 11] = RpGpioFunction.NONE;
            pinMapping[22, 0] = RpGpioFunction.NONE;
            pinMapping[22, 1] = RpGpioFunction.SPI0_SCK;
            pinMapping[22, 2] = RpGpioFunction.UART1_CTS;
            pinMapping[22, 3] = RpGpioFunction.I2C1_SDA;
            pinMapping[22, 4] = RpGpioFunction.PWM3_A;
            pinMapping[22, 5] = RpGpioFunction.SIO;
            pinMapping[22, 6] = RpGpioFunction.PIO0;
            pinMapping[22, 7] = RpGpioFunction.PIO1;
            pinMapping[22, 8] = RpGpioFunction.PIO2;
            pinMapping[22, 9] = RpGpioFunction.CLOCK_GPIN1;
            pinMapping[22, 10] = RpGpioFunction.USB_VBUS_DET;
            pinMapping[22, 11] = RpGpioFunction.UART1_TX;
            pinMapping[23, 0] = RpGpioFunction.NONE;
            pinMapping[23, 1] = RpGpioFunction.SPI0_TX;
            pinMapping[23, 2] = RpGpioFunction.UART1_RTS;
            pinMapping[23, 3] = RpGpioFunction.I2C1_SCL;
            pinMapping[23, 4] = RpGpioFunction.PWM3_B;
            pinMapping[23, 5] = RpGpioFunction.SIO;
            pinMapping[23, 6] = RpGpioFunction.PIO0;
            pinMapping[23, 7] = RpGpioFunction.PIO1;
            pinMapping[23, 8] = RpGpioFunction.PIO2;
            pinMapping[23, 9] = RpGpioFunction.CLOCK_GPOUT1;
            pinMapping[23, 10] = RpGpioFunction.USB_VBUS_EN;
            pinMapping[23, 11] = RpGpioFunction.UART1_RX;
            pinMapping[24, 0] = RpGpioFunction.NONE;
            pinMapping[24, 1] = RpGpioFunction.SPI1_RX;
            pinMapping[24, 2] = RpGpioFunction.UART1_TX;
            pinMapping[24, 3] = RpGpioFunction.I2C0_SDA;
            pinMapping[24, 4] = RpGpioFunction.PWM4_A;
            pinMapping[24, 5] = RpGpioFunction.SIO;
            pinMapping[24, 6] = RpGpioFunction.PIO0;
            pinMapping[24, 7] = RpGpioFunction.PIO1;
            pinMapping[24, 8] = RpGpioFunction.PIO2;
            pinMapping[24, 9] = RpGpioFunction.CLOCK_GPOUT2;
            pinMapping[24, 10] = RpGpioFunction.USB_OVCUR_DET;
            pinMapping[24, 11] = RpGpioFunction.NONE;
            pinMapping[25, 0] = RpGpioFunction.NONE;
            pinMapping[25, 1] = RpGpioFunction.SPI1_CSn;
            pinMapping[25, 2] = RpGpioFunction.UART1_RX;
            pinMapping[25, 3] = RpGpioFunction.I2C0_SCL;
            pinMapping[25, 4] = RpGpioFunction.PWM4_B;
            pinMapping[25, 5] = RpGpioFunction.SIO;
            pinMapping[25, 6] = RpGpioFunction.PIO0;
            pinMapping[25, 7] = RpGpioFunction.PIO1;
            pinMapping[25, 8] = RpGpioFunction.PIO2;
            pinMapping[25, 9] = RpGpioFunction.CLOCK_GPOUT3;
            pinMapping[25, 10] = RpGpioFunction.USB_VBUS_DET;
            pinMapping[25, 11] = RpGpioFunction.NONE;
            pinMapping[26, 0] = RpGpioFunction.NONE;
            pinMapping[26, 1] = RpGpioFunction.SPI1_SCK;
            pinMapping[26, 2] = RpGpioFunction.UART1_CTS;
            pinMapping[26, 3] = RpGpioFunction.I2C1_SDA;
            pinMapping[26, 4] = RpGpioFunction.PWM5_A;
            pinMapping[26, 5] = RpGpioFunction.SIO;
            pinMapping[26, 6] = RpGpioFunction.PIO0;
            pinMapping[26, 7] = RpGpioFunction.PIO1;
            pinMapping[26, 8] = RpGpioFunction.PIO2;
            pinMapping[26, 9] = RpGpioFunction.NONE;
            pinMapping[26, 10] = RpGpioFunction.USB_VBUS_EN;
            pinMapping[26, 11] = RpGpioFunction.UART1_TX;
            pinMapping[27, 0] = RpGpioFunction.NONE;
            pinMapping[27, 1] = RpGpioFunction.SPI1_TX;
            pinMapping[27, 2] = RpGpioFunction.UART1_RTS;
            pinMapping[27, 3] = RpGpioFunction.I2C1_SCL;
            pinMapping[27, 4] = RpGpioFunction.PWM5_B;
            pinMapping[27, 5] = RpGpioFunction.SIO;
            pinMapping[27, 6] = RpGpioFunction.PIO0;
            pinMapping[27, 7] = RpGpioFunction.PIO1;
            pinMapping[27, 8] = RpGpioFunction.PIO2;
            pinMapping[27, 9] = RpGpioFunction.NONE;
            pinMapping[27, 10] = RpGpioFunction.USB_OVCUR_DET;
            pinMapping[27, 11] = RpGpioFunction.UART1_RX;
            pinMapping[28, 0] = RpGpioFunction.NONE;
            pinMapping[28, 1] = RpGpioFunction.SPI1_RX;
            pinMapping[28, 2] = RpGpioFunction.UART0_TX;
            pinMapping[28, 3] = RpGpioFunction.I2C0_SDA;
            pinMapping[28, 4] = RpGpioFunction.PWM6_A;
            pinMapping[28, 5] = RpGpioFunction.SIO;
            pinMapping[28, 6] = RpGpioFunction.PIO0;
            pinMapping[28, 7] = RpGpioFunction.PIO1;
            pinMapping[28, 8] = RpGpioFunction.PIO2;
            pinMapping[28, 9] = RpGpioFunction.NONE;
            pinMapping[28, 10] = RpGpioFunction.USB_VBUS_DET;
            pinMapping[28, 11] = RpGpioFunction.NONE;
            pinMapping[29, 0] = RpGpioFunction.NONE;
            pinMapping[29, 1] = RpGpioFunction.SPI1_CSn;
            pinMapping[29, 2] = RpGpioFunction.UART0_RX;
            pinMapping[29, 3] = RpGpioFunction.I2C0_SCL;
            pinMapping[29, 4] = RpGpioFunction.PWM6_B;
            pinMapping[29, 5] = RpGpioFunction.SIO;
            pinMapping[29, 6] = RpGpioFunction.PIO0;
            pinMapping[29, 7] = RpGpioFunction.PIO1;
            pinMapping[29, 8] = RpGpioFunction.PIO2;
            pinMapping[29, 9] = RpGpioFunction.NONE;
            pinMapping[29, 10] = RpGpioFunction.USB_VBUS_EN;
            pinMapping[29, 11] = RpGpioFunction.NONE;
            pinMapping[30, 0] = RpGpioFunction.NONE;
            pinMapping[30, 1] = RpGpioFunction.SPI1_SCK;
            pinMapping[30, 2] = RpGpioFunction.UART0_CTS;
            pinMapping[30, 3] = RpGpioFunction.I2C1_SDA;
            pinMapping[30, 4] = RpGpioFunction.PWM7_A;
            pinMapping[30, 5] = RpGpioFunction.SIO;
            pinMapping[30, 6] = RpGpioFunction.PIO0;
            pinMapping[30, 7] = RpGpioFunction.PIO1;
            pinMapping[30, 8] = RpGpioFunction.PIO2;
            pinMapping[30, 9] = RpGpioFunction.NONE;
            pinMapping[30, 10] = RpGpioFunction.USB_OVCUR_DET;
            pinMapping[30, 11] = RpGpioFunction.UART0_TX;
            pinMapping[31, 0] = RpGpioFunction.NONE;
            pinMapping[31, 1] = RpGpioFunction.SPI1_TX;
            pinMapping[31, 2] = RpGpioFunction.UART0_RTS;
            pinMapping[31, 3] = RpGpioFunction.I2C1_SCL;
            pinMapping[31, 4] = RpGpioFunction.PWM7_B;
            pinMapping[31, 5] = RpGpioFunction.SIO;
            pinMapping[31, 6] = RpGpioFunction.PIO0;
            pinMapping[31, 7] = RpGpioFunction.PIO1;
            pinMapping[31, 8] = RpGpioFunction.PIO2;
            pinMapping[31, 9] = RpGpioFunction.NONE;
            pinMapping[31, 10] = RpGpioFunction.USB_VBUS_DET;
            pinMapping[31, 11] = RpGpioFunction.UART0_RX;
            pinMapping[32, 0] = RpGpioFunction.NONE;
            pinMapping[32, 1] = RpGpioFunction.SPI0_RX;
            pinMapping[32, 2] = RpGpioFunction.UART0_TX;
            pinMapping[32, 3] = RpGpioFunction.I2C0_SDA;
            pinMapping[32, 4] = RpGpioFunction.PWM8_A;
            pinMapping[32, 5] = RpGpioFunction.SIO;
            pinMapping[32, 6] = RpGpioFunction.PIO0;
            pinMapping[32, 7] = RpGpioFunction.PIO1;
            pinMapping[32, 8] = RpGpioFunction.PIO2;
            pinMapping[32, 9] = RpGpioFunction.NONE;
            pinMapping[32, 10] = RpGpioFunction.USB_VBUS_EN;
            pinMapping[32, 11] = RpGpioFunction.NONE;
            pinMapping[33, 0] = RpGpioFunction.NONE;
            pinMapping[33, 1] = RpGpioFunction.SPI0_CSn;
            pinMapping[33, 2] = RpGpioFunction.UART0_RX;
            pinMapping[33, 3] = RpGpioFunction.I2C0_SCL;
            pinMapping[33, 4] = RpGpioFunction.PWM8_B;
            pinMapping[33, 5] = RpGpioFunction.SIO;
            pinMapping[33, 6] = RpGpioFunction.PIO0;
            pinMapping[33, 7] = RpGpioFunction.PIO1;
            pinMapping[33, 8] = RpGpioFunction.PIO2;
            pinMapping[33, 9] = RpGpioFunction.NONE;
            pinMapping[33, 10] = RpGpioFunction.USB_OVCUR_DET;
            pinMapping[33, 11] = RpGpioFunction.NONE;
            pinMapping[34, 0] = RpGpioFunction.NONE;
            pinMapping[34, 1] = RpGpioFunction.SPI0_SCK;
            pinMapping[34, 2] = RpGpioFunction.UART0_CTS;
            pinMapping[34, 3] = RpGpioFunction.I2C1_SDA;
            pinMapping[34, 4] = RpGpioFunction.PWM9_A;
            pinMapping[34, 5] = RpGpioFunction.SIO;
            pinMapping[34, 6] = RpGpioFunction.PIO0;
            pinMapping[34, 7] = RpGpioFunction.PIO1;
            pinMapping[34, 8] = RpGpioFunction.PIO2;
            pinMapping[34, 9] = RpGpioFunction.NONE;
            pinMapping[34, 10] = RpGpioFunction.USB_VBUS_DET;
            pinMapping[34, 11] = RpGpioFunction.UART0_TX;
            pinMapping[35, 0] = RpGpioFunction.NONE;
            pinMapping[35, 1] = RpGpioFunction.SPI0_TX;
            pinMapping[35, 2] = RpGpioFunction.UART0_RTS;
            pinMapping[35, 3] = RpGpioFunction.I2C1_SCL;
            pinMapping[35, 4] = RpGpioFunction.PWM9_B;
            pinMapping[35, 5] = RpGpioFunction.SIO;
            pinMapping[35, 6] = RpGpioFunction.PIO0;
            pinMapping[35, 7] = RpGpioFunction.PIO1;
            pinMapping[35, 8] = RpGpioFunction.PIO2;
            pinMapping[35, 9] = RpGpioFunction.NONE;
            pinMapping[35, 10] = RpGpioFunction.USB_VBUS_EN;
            pinMapping[35, 11] = RpGpioFunction.UART0_RX;
            pinMapping[36, 0] = RpGpioFunction.NONE;
            pinMapping[36, 1] = RpGpioFunction.SPI0_RX;
            pinMapping[36, 2] = RpGpioFunction.UART1_TX;
            pinMapping[36, 3] = RpGpioFunction.I2C0_SDA;
            pinMapping[36, 4] = RpGpioFunction.PWM10_A;
            pinMapping[36, 5] = RpGpioFunction.SIO;
            pinMapping[36, 6] = RpGpioFunction.PIO0;
            pinMapping[36, 7] = RpGpioFunction.PIO1;
            pinMapping[36, 8] = RpGpioFunction.PIO2;
            pinMapping[36, 9] = RpGpioFunction.NONE;
            pinMapping[36, 10] = RpGpioFunction.USB_OVCUR_DET;
            pinMapping[36, 11] = RpGpioFunction.NONE;
            pinMapping[37, 0] = RpGpioFunction.NONE;
            pinMapping[37, 1] = RpGpioFunction.SPI0_CSn;
            pinMapping[37, 2] = RpGpioFunction.UART1_RX;
            pinMapping[37, 3] = RpGpioFunction.I2C0_SCL;
            pinMapping[37, 4] = RpGpioFunction.PWM10_B;
            pinMapping[37, 5] = RpGpioFunction.SIO;
            pinMapping[37, 6] = RpGpioFunction.PIO0;
            pinMapping[37, 7] = RpGpioFunction.PIO1;
            pinMapping[37, 8] = RpGpioFunction.PIO2;
            pinMapping[37, 9] = RpGpioFunction.NONE;
            pinMapping[37, 10] = RpGpioFunction.USB_VBUS_DET;
            pinMapping[37, 11] = RpGpioFunction.NONE;
            pinMapping[38, 0] = RpGpioFunction.NONE;
            pinMapping[38, 1] = RpGpioFunction.SPI0_SCK;
            pinMapping[38, 2] = RpGpioFunction.UART1_CTS;
            pinMapping[38, 3] = RpGpioFunction.I2C1_SDA;
            pinMapping[38, 4] = RpGpioFunction.PWM11_A;
            pinMapping[38, 5] = RpGpioFunction.SIO;
            pinMapping[38, 6] = RpGpioFunction.PIO0;
            pinMapping[38, 7] = RpGpioFunction.PIO1;
            pinMapping[38, 8] = RpGpioFunction.PIO2;
            pinMapping[38, 9] = RpGpioFunction.NONE;
            pinMapping[38, 10] = RpGpioFunction.USB_VBUS_EN;
            pinMapping[38, 11] = RpGpioFunction.UART1_TX;
            pinMapping[39, 0] = RpGpioFunction.NONE;
            pinMapping[39, 1] = RpGpioFunction.SPI0_TX;
            pinMapping[39, 2] = RpGpioFunction.UART1_RTS;
            pinMapping[39, 3] = RpGpioFunction.I2C1_SCL;
            pinMapping[39, 4] = RpGpioFunction.PWM11_B;
            pinMapping[39, 5] = RpGpioFunction.SIO;
            pinMapping[39, 6] = RpGpioFunction.PIO0;
            pinMapping[39, 7] = RpGpioFunction.PIO1;
            pinMapping[39, 8] = RpGpioFunction.PIO2;
            pinMapping[39, 9] = RpGpioFunction.NONE;
            pinMapping[39, 10] = RpGpioFunction.USB_OVCUR_DET;
            pinMapping[39, 11] = RpGpioFunction.UART1_RX;
            pinMapping[40, 0] = RpGpioFunction.NONE;
            pinMapping[40, 1] = RpGpioFunction.SPI1_RX;
            pinMapping[40, 2] = RpGpioFunction.UART1_TX;
            pinMapping[40, 3] = RpGpioFunction.I2C0_SDA;
            pinMapping[40, 4] = RpGpioFunction.PWM8_A;
            pinMapping[40, 5] = RpGpioFunction.SIO;
            pinMapping[40, 6] = RpGpioFunction.PIO0;
            pinMapping[40, 7] = RpGpioFunction.PIO1;
            pinMapping[40, 8] = RpGpioFunction.PIO2;
            pinMapping[40, 9] = RpGpioFunction.NONE;
            pinMapping[40, 10] = RpGpioFunction.USB_VBUS_DET;
            pinMapping[40, 11] = RpGpioFunction.NONE;
            pinMapping[41, 0] = RpGpioFunction.NONE;
            pinMapping[41, 1] = RpGpioFunction.SPI1_CSn;
            pinMapping[41, 2] = RpGpioFunction.UART1_RX;
            pinMapping[41, 3] = RpGpioFunction.I2C0_SCL;
            pinMapping[41, 4] = RpGpioFunction.PWM8_B;
            pinMapping[41, 5] = RpGpioFunction.SIO;
            pinMapping[41, 6] = RpGpioFunction.PIO0;
            pinMapping[41, 7] = RpGpioFunction.PIO1;
            pinMapping[41, 8] = RpGpioFunction.PIO2;
            pinMapping[41, 9] = RpGpioFunction.NONE;
            pinMapping[41, 10] = RpGpioFunction.USB_VBUS_EN;
            pinMapping[41, 11] = RpGpioFunction.NONE;
            pinMapping[42, 0] = RpGpioFunction.NONE;
            pinMapping[42, 1] = RpGpioFunction.SPI1_SCK;
            pinMapping[42, 2] = RpGpioFunction.UART1_CTS;
            pinMapping[42, 3] = RpGpioFunction.I2C1_SDA;
            pinMapping[42, 4] = RpGpioFunction.PWM9_A;
            pinMapping[42, 5] = RpGpioFunction.SIO;
            pinMapping[42, 6] = RpGpioFunction.PIO0;
            pinMapping[42, 7] = RpGpioFunction.PIO1;
            pinMapping[42, 8] = RpGpioFunction.PIO2;
            pinMapping[42, 9] = RpGpioFunction.NONE;
            pinMapping[42, 10] = RpGpioFunction.USB_OVCUR_DET;
            pinMapping[42, 11] = RpGpioFunction.UART1_TX;
            pinMapping[43, 0] = RpGpioFunction.NONE;
            pinMapping[43, 1] = RpGpioFunction.SPI1_TX;
            pinMapping[43, 2] = RpGpioFunction.UART1_RTS;
            pinMapping[43, 3] = RpGpioFunction.I2C1_SCL;
            pinMapping[43, 4] = RpGpioFunction.PWM9_B;
            pinMapping[43, 5] = RpGpioFunction.SIO;
            pinMapping[43, 6] = RpGpioFunction.PIO0;
            pinMapping[43, 7] = RpGpioFunction.PIO1;
            pinMapping[43, 8] = RpGpioFunction.PIO2;
            pinMapping[43, 9] = RpGpioFunction.NONE;
            pinMapping[43, 10] = RpGpioFunction.USB_VBUS_DET;
            pinMapping[43, 11] = RpGpioFunction.UART1_RX;
            pinMapping[44, 0] = RpGpioFunction.NONE;
            pinMapping[44, 1] = RpGpioFunction.SPI1_RX;
            pinMapping[44, 2] = RpGpioFunction.UART0_TX;
            pinMapping[44, 3] = RpGpioFunction.I2C0_SDA;
            pinMapping[44, 4] = RpGpioFunction.PWM10_A;
            pinMapping[44, 5] = RpGpioFunction.SIO;
            pinMapping[44, 6] = RpGpioFunction.PIO0;
            pinMapping[44, 7] = RpGpioFunction.PIO1;
            pinMapping[44, 8] = RpGpioFunction.PIO2;
            pinMapping[44, 9] = RpGpioFunction.NONE;
            pinMapping[44, 10] = RpGpioFunction.USB_VBUS_EN;
            pinMapping[44, 11] = RpGpioFunction.NONE;
            pinMapping[45, 0] = RpGpioFunction.NONE;
            pinMapping[45, 1] = RpGpioFunction.SPI1_CSn;
            pinMapping[45, 2] = RpGpioFunction.UART0_RX;
            pinMapping[45, 3] = RpGpioFunction.I2C0_SCL;
            pinMapping[45, 4] = RpGpioFunction.PWM10_B;
            pinMapping[45, 5] = RpGpioFunction.SIO;
            pinMapping[45, 6] = RpGpioFunction.PIO0;
            pinMapping[45, 7] = RpGpioFunction.PIO1;
            pinMapping[45, 8] = RpGpioFunction.PIO2;
            pinMapping[45, 9] = RpGpioFunction.NONE;
            pinMapping[45, 10] = RpGpioFunction.USB_OVCUR_DET;
            pinMapping[45, 11] = RpGpioFunction.NONE;
            pinMapping[46, 0] = RpGpioFunction.NONE;
            pinMapping[46, 1] = RpGpioFunction.SPI1_SCK;
            pinMapping[46, 2] = RpGpioFunction.UART0_CTS;
            pinMapping[46, 3] = RpGpioFunction.I2C1_SDA;
            pinMapping[46, 4] = RpGpioFunction.PWM11_A;
            pinMapping[46, 5] = RpGpioFunction.SIO;
            pinMapping[46, 6] = RpGpioFunction.PIO0;
            pinMapping[46, 7] = RpGpioFunction.PIO1;
            pinMapping[46, 8] = RpGpioFunction.PIO2;
            pinMapping[46, 9] = RpGpioFunction.NONE;
            pinMapping[46, 10] = RpGpioFunction.USB_VBUS_DET;
            pinMapping[46, 11] = RpGpioFunction.UART0_TX;
            pinMapping[47, 0] = RpGpioFunction.NONE;
            pinMapping[47, 1] = RpGpioFunction.SPI1_TX;
            pinMapping[47, 2] = RpGpioFunction.UART0_RTS;
            pinMapping[47, 3] = RpGpioFunction.I2C1_SCL;
            pinMapping[47, 4] = RpGpioFunction.PWM11_B;
            pinMapping[47, 5] = RpGpioFunction.SIO;
            pinMapping[47, 6] = RpGpioFunction.PIO0;
            pinMapping[47, 7] = RpGpioFunction.PIO1;
            pinMapping[47, 8] = RpGpioFunction.PIO2;
            pinMapping[47, 9] = RpGpioFunction.QMI_CS1n;
            pinMapping[47, 10] = RpGpioFunction.USB_VBUS_EN;
            pinMapping[47, 11] = RpGpioFunction.UART0_RX;
            return pinMapping;
        }
    }
}


